-- Run once in your Supabase SQL Editor. This uses a new table, not TeleCare tickets.
-- No local SQLite data is deleted or imported by this script.
begin;
create table if not exists public.leadflow_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 254),
  phone text not null default '' check (char_length(phone) <= 30),
  company text not null default '' check (char_length(company) <= 120),
  message text not null check (char_length(message) between 1 and 1500),
  status text not null default 'new' check (status in ('new','contacted','converted','lost')),
  consent boolean not null check (consent = true)
);
alter table public.leadflow_leads enable row level security;
revoke all on public.leadflow_leads from anon, authenticated;
revoke all on sequence public.leadflow_leads_id_seq from anon, authenticated;
grant usage on schema public to service_role;
grant select, insert, update on public.leadflow_leads to service_role;
grant usage, select on sequence public.leadflow_leads_id_seq to service_role;
commit;
